In [54]:
import pandas as pd
import numpy as np

In [55]:
book_data = pd.read_csv('data/ratings_books_users.csv')
book_data.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,City,State,Country
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,tyler,texas,usa
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,seattle,washington,usa
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,h,new south wales,australia
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,rijeka,NaN,croatia
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,rijeka,NaN,croatia

### Popularity Based Filtering

In [56]:
# Calculate number of ratings and average rating given to each book
ratings_book = book_data.groupby('Book-Title')['Book-Rating'].agg(['count', 'mean'])
ratings_book.reset_index(inplace=True)
ratings_book.head(10)

                                          Book-Title  count   mean
0   A Light in the Storm: The Civil War Diary of ...      4   2.25
1                              Always Have Popsicles      1   0.00
2               Apple Magic (The Collector's series)      1   0.00
3   Ask Lily (Young Women of Faith: Lily Series, ...      1   8.00
4   Beyond IBM: Leadership Marketing and Finance ...      1   0.00
5   Clifford Visita El Hospital (Clifford El Gran...      1   0.00
6                                       Dark Justice      1  10.00
7                                           Deceived      2   0.00
8   Earth Prayers From around the World: 365 Pray...     10   5.00
9   Final Fantasy Anthology: Official Strategy Gu...      4   5.00

In [57]:
# Keeping books with atleast 200 ratings
popular_books = ratings_book[ratings_book['count'] >= 200].sort_values(by='mean', ascending=False).head(50)
popular_books.shape

(50, 3)

In [58]:
popular_books = popular_books.merge(book_data, on='Book-Title', how='inner')[['Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher', 'Image-URL-M', 'mean', 'count']].drop_duplicates('Book-Title')
popular_books.shape

(50, 7)

In [59]:
popular_books.head(10)

,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-M,mean,count
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,2001,Scholastic,http://images.amazon.com/images/P/0439136369.0...,5.852804,428
428,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,2002,Scholastic Paperbacks,http://images.amazon.com/images/P/0439139600.0...,5.824289,387
815,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,2001,Scholastic,http://images.amazon.com/images/P/043936213X.0...,5.737410,278
1093,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,2003,Scholastic,http://images.amazon.com/images/P/043935806X.0...,5.501441,347
1440,Ender's Game (Ender Wiggins Saga (Paperback)),Orson Scott Card,1986,Tor Books,http://images.amazon.com/images/P/0812533550.0...,5.409639,249
1689,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439064864.0...,5.183453,556
2245,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339681.0...,5.007117,281
2526,The Fellowship of the Ring (The Lord of the Ri...,J. R. R. Tolkien,2001,Houghton Mifflin Company,http://images.amazon.com/images/P/0618129030.0...,4.948370,368
2894,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,1999,Arthur A. Levine Books,http://images.amazon.com/images/P/059035342X.0...,4.895652,575
3469,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,1999,Houghton Mifflin Company,http://images.amazon.com/images/P/0618002235.0...,4.880769,260

In [60]:
popular_books.tail(10)

,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-M,mean,count
15891,The Bean Trees,Barbara Kingsolver,1998,HarperTorch,http://images.amazon.com/images/P/0061097314.0...,4.087404,389
16280,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,1995,Health Communications,http://images.amazon.com/images/P/1558743669.0...,4.086792,265
16545,ANGELA'S ASHES,Frank McCourt,1996,Scribner,http://images.amazon.com/images/P/0684874350.0...,4.075269,279
16824,High Fidelity,Nick Hornby,1996,Riverhead Books,http://images.amazon.com/images/P/1573225517.0...,4.056680,247
17071,Good in Bed,Jennifer Weiner,2002,Washington Square Press,http://images.amazon.com/images/P/0743418174.0...,4.055102,490
17561,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,2002,Perennial,http://images.amazon.com/images/P/0060938455.0...,4.037383,321
17882,American Gods,Neil Gaiman,2002,HarperTorch,http://images.amazon.com/images/P/0380789035.0...,4.006623,302
18184,Skipping Christmas,JOHN GRISHAM,2001,Doubleday,http://images.amazon.com/images/P/0385505833.0...,4.006211,322
18506,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,1996,Tyndale House Publishers,http://images.amazon.com/images/P/0842329129.0...,4.003145,318
18824,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,2002,Knopf Books for Young Readers,http://images.amazon.com/images/P/037582345X.0...,4.000000,336

In [61]:
import pickle
pickle.dump(popular_books, open('data/popular_books.pkl', 'wb'))

### Collaborative Filtering Based

In [62]:
# Keep the data for users who have rated atleast 200 books
users_rated = book_data.groupby('User-ID').count()['Book-Rating'] > 200
users_rated = users_rated[users_rated].index.tolist()
filtered_rating = book_data[book_data['User-ID'].isin(users_rated)]

filtered_rating.shape

(467518, 13)

In [63]:
# Filtering Books with atleast 50 ratings
filtered_books = filtered_rating.groupby('Book-Title').count()['Book-Rating'] >= 50
filtered_books = filtered_books[filtered_books].index.tolist()
final_book = filtered_rating[book_data['Book-Title'].isin(filtered_books)]

final_book.shape

C:\Users\bhavy\AppData\Local\Temp\ipykernel_21344\341777286.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  final_book = filtered_rating[book_data['Book-Title'].isin(filtered_books)]

(57835, 13)

In [64]:
final_book.drop_duplicates(inplace=True)
final_book.shape

C:\Users\bhavy\AppData\Local\Temp\ipykernel_21344\3081665659.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_book.drop_duplicates(inplace=True)

(57835, 13)

In [65]:
# Pivot table of the data
pivot_table_data = final_book.pivot_table(index='Book-Title', columns='User-ID', values='Book-Rating').fillna(0)

In [66]:
from sklearn.metrics.pairwise import cosine_similarity

In [67]:
similarity_score = cosine_similarity(pivot_table_data)
similarity_score.shape

(698, 698)

In [76]:
def recommend_books(book_name):
    # index fetch
    index = np.where(pivot_table_data.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_score[index])),key=lambda x:x[1],reverse=True)[1:5]
    
    data = []
    for i in similar_items:
        item = []
        temp_df = book_data[book_data['Book-Title'] == pivot_table_data.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Publisher'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Year-Of-Publication'].values))
        
        data.append(item)
    
    return data

In [77]:
recommend_books('The Notebook')

[['A Walk to Remember',
  'Nicholas Sparks',
  'http://images.amazon.com/images/P/0446608955.01.MZZZZZZZ.jpg',
  'Warner Books',
  2000],
 ['The Rescue',
  'Nicholas Sparks',
  'http://images.amazon.com/images/P/0446610399.01.MZZZZZZZ.jpg',
  'Warner Books',
  2001],
 ['One Door Away from Heaven',
  'Dean R. Koontz',
  'http://images.amazon.com/images/P/0553582755.01.MZZZZZZZ.jpg',
  'Bantam Books',
  2002],
 ['Toxin',
  'Robin Cook',
  'http://images.amazon.com/images/P/0425167097.01.MZZZZZZZ.jpg',
  'Berkley Pub Group',
  1999]]

In [78]:
import pickle
pickle.dump(popular_books,open('data/popular_books.pkl','wb'))

In [80]:
book_data = book_data.drop_duplicates('Book-Title')

In [82]:
pickle.dump(pivot_table_data,open('data/pivot_table_data.pkl','wb'))
pickle.dump(book_data,open('data/book_data.pkl','wb'))
pickle.dump(similarity_score,open('data/similarity_score.pkl','wb'))